### DISCUSSION TITLE
How to reference plugins in docker-compose?

### DISCUSSION THREAD

**Discussion by shimizurei** [TimWolla/docker-adminer#124] [Q&A] [answered]
I am testing out adminer and I cannot get it to run when I add the plugin line. According to the logs, I get an exit code 255.

### Compose File

```yaml
version: '3.7'
services:
    adminer:
        image: 'adminer:latest'
        restart: always
        ports:
            - '8080:8080'
        environment:
            - 'ADMINER_DESIGN=dracula'
            - 'ADMINER_PLUGINS=plugin dump-json dump-zip login-password-less'

    mysql_db:
        image: 'mariadb:10.7'
        command: '--default-authentication-plugin=mysql_native_password'
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: rootpassword
```

**Comment by methbkts** [comment]
@shimizurei AFAIK you don't need to put `plugin` into `ADMINER_PLUGINS` env var
also, you need to bind-mount `login-password-less`
so your compose file should look like this
```yaml
services:
  adminer:
    image: 'adminer:latest'
      restart: always
      ports:
        - '8080:8080'
      volumes:
        - ./plugins/login-password-less.php:/var/www/html/plugins-enabled/login-password-less.php
      environment:
        - 'ADMINER_DESIGN=dracula'
        - 'ADMINER_PLUGINS=dump-json dump-zip'
```

**Comment by shimizurei** [comment, marked as answer]
Found the answer [here](https://github.com/TimWolla/docker-adminer/issues/50#issuecomment-473565963).

Compose file (adminer section) ultimately looks like this:

```yaml
services:
  adminer:
    image: 'adminer:latest'
      restart: always
      ports:
        - '8080:8080'
      volumes:
        - ./plugins/login-password-less.php:/var/www/html/plugins-enabled/login-password-less.php
      environment:
        - 'ADMINER_DESIGN=dracula'
        - 'ADMINER_PLUGINS=dump-json dump-zip' # #### REMOVE any plugins in a bind mount from the list
```
