### ISSUE TITLE
tinymce Js not loading in docker 

### ISSUE THREAD

**Issue by mtariqsajid** [TimWolla/docker-adminer#101]
This is the docker-compose.yml
```yml
version: '3.9'

services:
  mysql_db:
    image: mysql:latest
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./mysql/data:/var/lib/mysql
    environment:
        MYSQL_ROOT_USER: root
        MYSQL_ROOT_PASSWORD: secret123
        MYSQL_DATABASE: homestead
        MYSQL_USER: laravel
        MYSQL_PASSWORD: laravel

  adminer:
    image: adminer:latest
    restart: always
    environment: 
      ADMINER_DEFAULT_SERVER: mysql_db
      ADMINER_DEFAULT_USER: root
      ADMINER_DEFAULT_PASSWORD: secret123
      ADMINER_PLUGINS: 'tables-filter tinymce'
    depends_on:
      - mysql_db
    ports:
      - 8080:8080

networks:
  default:
    external:
      name: larvel-network
```

this is error I am getting 
![image](https://user-images.githubusercontent.com/68206359/117590224-cc1a4480-b147-11eb-8523-e6059b60b8ed.png)
