### ISSUE TITLE
Adminer Theme Doesn't Show

### ISSUE THREAD

**Issue by mtpultz** [TimWolla/docker-adminer#12]
Adding the ADMINER_DESIGN environment variable doesn't change the theme.  Using this docker-compose.yml and dockerfile, where the dockerfile for adminer is just defaults, since env_file takes precedence.

**Docker Compose**

```
version: '2'

services:
  server:
    container_name: server
    build:
      context: .
      dockerfile: .docker/node.${APP_ENV}.dockerfile
    ports:
      - "${NODE_PORT}:3000"
    volumes:
      - ${NODE_SRC_PATH}:${NODE_CONTAINER_PATH}
    working_dir: ${NODE_WORKING_DIR}
    env_file:
      - ./.docker/env/node.${APP_ENV}.env
    depends_on:
      - db
    networks:
      - app-network

  db:
    container_name: db
    image: mysql
    build:
      context: .
      dockerfile: .docker/mysql.dockerfile
    ports:
      - "3306:3306"
    env_file:
      - ./.docker/env/mysql.${APP_ENV}.env
    networks:
      - app-network

  db_manager:
    container_name: db_manager
    image: adminer
    build:
      context: .
      dockerfile: .docker/adminer.dockerfile
    ports:
      - "8080:8080"
    env_file:
      - ./.docker/env/adminer.env
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
```

**Adminer Env**

```
ADMINER_DESIGN=pepa-linha
```

**Docker File**

```
# Pull in image
FROM adminer:latest

MAINTAINER Source Reactor

# Provide environmental variables
# ---
# NOTE:
# Environment precedents is taken from the environment key, then the .env
# file, and finally from ENV entries in the dockerfile, which represent
# development defaults
# ---
ENV ADMINER_DESIGN=pepa-linha
```
