### ISSUE TITLE
Preconfigured authoriziation

### ISSUE THREAD

**Issue by kler** [TimWolla/docker-adminer#13]
A nice feature would be if it was possible to pass `server`, `username`, `password` and `database` as parameters to the docker image.

In that way it would be very convenient to bundle adminer in a development stack docker-compose and provide a one-click access to the database.

I'm thinking that `docker-compose.yml` could look something like this:

    adminer:
        image: adminer
        ports: 8080:8080
        environment:
        - ADMINER_SERVER=db
        - ADMINER_USER=root
        - ADMINER_PASSWORD=secret
        - ADMINER_DATABASE=mydatabase

This would make adminer either 1) just pre-fill the values in the form, or 2) auto-login.

I guess this request would also require changes in adminer itself though.

**Comment by TimWolla** [comment]
I don't want to modify adminer any more than I already did (prefilling `db` as the database host and that is only because `localhost` just doesn't make sense). You can do this easily with a custom image and a little adminer plugin though:

```
<?php
// Add this file as /var/www/html/plugins-enabled/autologin.php in the adminer image
class Autologin {
  // see: https://github.com/vrana/adminer/blob/7af1ee3702420620641d075ebfd54d4b1d220409/adminer/include/adminer.inc.php#L18-L20
  function credentials() {
    if (!empty($_GET['username'])) return array(SERVER, $_GET["username"], get_password());
    return array($_ENV['ADMINER_SERVER'], $_ENV['ADMINER_USER'], $_ENV['ADMINER_PASSWORD']);
  }
}

return new Autologin();
```

```
FROM adminer

COPY autologin.php /var/www/html/plugins-enabled/
```

When no credentials are put in and the form is submitted the credentials from the environment are used, otherwise the credentials from the form are used.

**Comment by kler** [comment]
Ok, thx for pointing me (or someone else) in the right direction!

**Comment by bserem** [comment]
> When no credentials are put in and the form is submitted the credentials from the environment are used, otherwise the credentials from the form are used.

This seems to have changed in recent years, adminer does not allow you to login without entering credentials, it displays a message:
> Adminer does not support accessing a database without a password, [more information](https://www.adminer.org/en/password/).

Adding any random credentials works with the plugin provided in this thread, but it is not a solution. Any info on the matter would be nice.

**Comment by raneomik** [comment]
Hi, I also bumped on the same issue and it seems to have been changed again  (I'm under adminer 5.2.1) since https://github.com/TimWolla/docker-adminer/issues/13#issuecomment-2023730622 solution blocks at the login page.

managed to make it work with this piece of config : 

```yml
# compose.yaml

services:
  postgres:
    image: postgres:latest
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: dev

  adminer:
    image: adminer:latest
    restart: unless-stopped
    environment:
      ADMINER_DEFAULT_SERVER: postgres
      ADMINER_DEFAULT_USERNAME: user
      ADMINER_DEFAULT_PASSWORD: password
      ADMINER_DEFAULT_DB: dev
    ports:
      - "3344:8080"
    depends_on:
      - postgres
    configs:
      - source: adminer-index.php
        target: /var/www/html/index.php
        mode: 0755 # avoid Warning & Fatal error : "Failed to open stream: Permission denied --> Failed opening required '/var/www/html/index.php' (include_path='.:/usr/local/lib/php') in Unknown on line 0"

configs:
  adminer-index.php:
    content: |
      <?php
        if(!count($$_GET)) {
          $$_POST['auth'] = [
            'server' => $$_ENV['ADMINER_DEFAULT_SERVER'],
            'driver' => 'server', /* seems to autodetect the driver from server settings */
            'username' => $$_ENV['ADMINER_DEFAULT_USERNAME'],
            'password' => $$_ENV['ADMINER_DEFAULT_PASSWORD'],
            'db' => $$_ENV['ADMINER_DEFAULT_DB'],
          ];
        }
        include './adminer.php';

```
