### ISSUE TITLE
Error connecting to MS SQL Server 2019 running in a docker container

### ISSUE THREAD

**Issue by Lancer92** [TimWolla/docker-adminer#130]
I use next docker-compose instructions.
```
services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
      - ${DATABASE_PORT}:1433
    volumes:
      - ./.data/db:/var/lib/mssql/data
    environment:
      ACCEPT_EULA: -Y
      MSSQL_SA_USER: ${DATABASE_USERNAME}
      MSSQL_SA_PASSWORD: ${DATABASE_PASSWORD}
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
```
However, it works from code (Node.js, TypeORM) but it's shows error when trying to connect to adminer:
`SQLSTATE[HY000] Unable to connect: Adaptive Server is unavailable or does not exist (localhost) (severity 9)`

OS: macOS 12.6
browser: Chrome Version 108.0.5359.98 (Official Build) (x86_64) 
NodeJS: 18.12.1
