### ISSUE TITLE
How to configure a sub-URL ?

### ISSUE THREAD

**Issue by konvergence** [TimWolla/docker-adminer#14]
Hi, 
Is it possible to use a sub-url path instead of  only "/" root URL ?
I would like to usr a sub-URL . Example : https://mydomain/adminer/ instead of https://myadminer/

Regards

**Comment by TimWolla** [comment]
> Is it possible to use a sub-url path instead of only "/" root URL ?

It is. For more specific advice I need to know which image you are using (FastCGI or Standalone?, Which Reverse Proxy or Webserver?).

**Comment by konvergence** [comment]
Standalone

**Comment by TimWolla** [comment]
Use a reverse proxy of your choice to map an arbitrary path to the `/index.php` of the container.

**Comment by jalogisch** [comment]
@TimWolla maybe I'm to stupid, but the following did not work for me:

The Part of my `docker_compose.yml`
```

  adminer:
    image: adminer
    container_name: adminer
    hostname: adminer
    mem_limit: 128m
    restart: always
    environment:
      - TZ=Europe/Berlin
    ports:
      - 127.0.0.1:8082:8080
    depends_on:
      - db
```

The part of my NGINX configuration

```
  location /adminer/ {
    proxy_set_header Host $host;
    proxy_redirect off;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_pass http://127.0.0.1:8082/;
  }
```

but the above will not let me login, as after login the page is redirected to `/` removing the subfolder.

Maybe you can document this a little more.

thx

**Comment by delfer** [comment]
@TimWolla it is still an issue

**Comment by vesamet** [comment]
This config works fine for me :
`location /adminer {
        proxy_pass  http://localhost:3000;
        proxy_set_header    Host                $http_host;
        proxy_set_header    X-Real-IP           $remote_addr;
        proxy_set_header    X-Forwarded-For     $proxy_add_x_forwarded_for;
    }`

But it doesn't work if pointing to another server like this
`
location /adminer {
        proxy_set_header X-Forwarded-Host $host:$server_port;
        proxy_set_header X-Forwarded-Server $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_pass http://XX.XX.XX.X:3000/;
    }
`
@TimWolla Do you know a possible fix ? I tried the fastcgi method but it's not working as expected.
Thank you in advance if you happen to have the time!

**Comment by TimWolla** [comment]
@vesamet You misconfigured your `proxy_pass` directive. Quoting from the nginx documentation (http://nginx.org/en/docs/http/ngx_http_proxy_module.html#proxy_pass):

> If the proxy_pass directive is specified with a URI, then when a request is passed to the server, the part of a normalized request URI matching the location is replaced by a URI specified in the directive:

Replacing `proxy_pass http://XX.XX.XX.X:3000/;` with `proxy_pass http://XX.XX.XX.X:3000;` should fix the issue for you.

**Comment by v-nalvarez** [comment]
Hi @TimWolla is there any way to may this works with Apache? I have this setting and I am facing the same issue, adminer.css is being fetch at www.example.com/adminer.css instead of www.example.com/myfolder/adminer.css

Other than the style, everything else is working correctly.

**Comment by TimWolla** [comment]
@v-nalvarez I don't have any Apache experience, but this looks like you're using the standalone version. Putting Adminer into a subdirectory with this Docker image is only well-supported if you're using FastCGI. See:

https://github.com/TimWolla/docker-adminer/issues/14#issuecomment-385508119

**Comment by CosasDePuma** [comment]
> Hi @TimWolla is there any way to get this to work with Apache? I have this setting and I am facing the same issue proxypass /myfolder/adminer http://x.x.x.x:8080 proxypassreverse /myfolder/adminer http://x.x.x.x:8080
> 
> ```
>     <Location /myfolder/adminer>
>             AllowOverride All
>             Order allow,deny
>             Allow from all
>     </Location>
> ```
> 
> adminer.css is being fetched from [www.example.com/adminer.css](http://www.example.com/adminer.css) instead of [www.example.com/myfolder/adminer.css](http://www.example.com/myfolder/adminer.css)
> 
> Other than the style, everything else is working correctly.

I think I've found the reason why the theme won't load.
The CSS loads the src "adminer.css", so if your path does NOT end with the slash (/), the last part is replaced with "adminer.css".

For simplicity:

| Base URL | Theme Request | Is CSS loaded correctly? |
| --- | --- | --- |
| https://sub.example.tld/sub/db | https://sub.example.tld/sub/adminer.css | Does not load the CSS |
| https://sub.example.tld/sub/db/ | https://sub.example.tld/sub/db/adminer.css | Loads the CSS 🎉 |

So it is necessary to FORCE the slash to be present, with configurations like these, for example:

**Nginx** (not tested):

```
    <Location /sub/db/> # Path ends with slash
            AllowOverride All
            Order allow,deny
            Allow from all
    </Location>
```

**Traefik** (tested and working as expected):

```yaml
labels:
  traefik.enable: true
  traefik.http.routers.adminer.rule: Host(`sub.example.tld`) && PathPrefix(`/sub/db/`) # Path ends with slash
  traefik.http.routers.adminer.entrypoints: https
  traefik.http.routers.adminer.service: adminer
  traefik.http.routers.adminer.middlewares: adminer
  traefik.http.services.adminer.loadbalancer.server.port: 8080
  traefik.http.middlewares.adminer.stripprefix.prefixes: /sub/db
```
