### ISSUE TITLE
Increase allowed memory

### ISSUE THREAD

**Issue by Creeperface01** [TimWolla/docker-adminer#145]
I'm getting `Allowed memory size of 1073741824 bytes exhausted` error when importing larger dumps and could not find a way to increase allowed limit.
Would be nice to provide it as an option.

**Comment by Creeperface01** [comment]
> Under what circumstances are you seeing that error?

Happens when importing larger dumps (around 50-70 MB)
Sorry for not mentioning, updated description.

**Comment by Miras4207** [comment]
```

```

```
adminer:
        image: adminer
        ports:
            - 8080:8080
        volumes:
            - ./php.local.ini:/etc/php/7.4/cli/conf.d/local.ini
```

**Comment by Miras4207** [comment]
You can load your local PHP configuration using `docker-compose.yml` like this:

```yaml
services:
    adminer:
        image: adminer:4.8.1
        ports:
            - 8080:8080
        volumes:
            - ./php.local.ini:/etc/php/7.4/cli/conf.d/php.local.ini
```

php.local.ini
```ini
post_max_size = 516M
upload_max_filesize = 516M
```

If the PHP version changes in future versions of adminer image, you can find the correct path by running `php --ini` inside the container.
