### ISSUE TITLE
[bug fix] designs/hydra/adminer.css missing,        ADMINER_DESIGN: hydra

### ISSUE THREAD

**Issue by geekyouth** [TimWolla/docker-adminer#146]
```yaml

...
  adminer:
    image: adminer:4.8.1
    hostname: adminer
    restart: unless-stopped
    ports:
      - "8080:8080"
    command: |
      php -S [::]:8080 -t /var/www/html;
      wget https://raw.githubusercontent.com/Niyko/Hydra-Dark-Theme-for-Adminer/master/adminer.css -O /var/www/html/designs/hydra/adminer.css
    environment:
      ADMINER_DEFAULT_SERVER: db
      ADMINER_DESIGN: hydra
    networks:
      - external
...
```

![image](https://github.com/TimWolla/docker-adminer/assets/12899262/686d7302-df24-4c45-898a-14543f892be8)
