### ISSUE TITLE
[bug] ADMINER_DESIGN: hydra, not show all columns if too much

### ISSUE THREAD

**Issue by geekyouth** [TimWolla/docker-adminer#166]
![image](https://github.com/TimWolla/docker-adminer/assets/12899262/ed358ae6-1217-4abd-b432-f6495cc6508d)

**Comment by geekyouth** [comment]
i have fix the bug by below docker-compose.yaml
```
services:
  adminer:
    image: adminer:4.8.1-standalone
    hostname: adminer
    restart: unless-stopped
    ports:
      - "58081:8080"
    environment:
      TZ: Asia/Shanghai
      ADMINER_DEFAULT_SERVER: mysql
      ADMINER_DESIGN: hydra
      ADMINER_PLUGINS: 'tables-filter tinymce dump-json'
    volumes:
      - ./hydra.css:/var/www/html/designs/hydra/adminer.css:ro  # fix hydra style
      - ./_docker-data/:/demo/:rw
      - ./sqlite.php:/var/www/html/plugins-enabled/sqlite.php # sqlite rw
```

hydra.css:  https://github.com/Niyko/Hydra-Dark-Theme-for-Adminer
