### ISSUE TITLE
Version 4.17.1 does not start

### ISSUE THREAD

**Issue by diximinga** [TimWolla/docker-adminer#183]
Version 4.17.1 does not start

`Container Log: /usr/local/bin/entrypoint.sh: line 14: can't create plugins-enabled/001-login-noroot.php: Permission denied`

compose.yaml:
```

 adminer:
    image: adminer:latest
    container_name: adminer
    hostname: adminer
    depends_on:
      - general-db
    links:
      - general-db
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - adminer:/var/www/html/
    environment:
      - ADMINER_PLUGINS=login-noroot
      - ADMINER_DEFAULT_SERVER=general-db
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.adminer.entrypoints=websecure"
      - "traefik.http.routers.adminer.rule=Host(`<myhost.fqdn>`)"
      - "traefik.http.routers.adminer.tls=true"
      - "traefik.http.routers.adminer.tls.certresolver=default"
      - "traefik.http.routers.adminer.middlewares=secHeaders@file"
      - "traefik.http.services.adminer.loadbalancer.server.port=8080"
    networks:
      - traefik_proxy
    restart: always
```

Rollback to 4.8.1 - and it works again
