### ISSUE TITLE
Healtchecks down work in latest

### ISSUE THREAD

**Issue by wildone** [TimWolla/docker-adminer#185]
This worked on `v4.8.1`  `sha256:2f7580903a1dd21cf033fe4b985a96c545713eba159de8e68b1c70c65b801923` does not work on latest.

```
  adminer:
    image: adminer
    restart: unless-stopped
    healthcheck:
      test: "curl -s -f http://localhost:8080 > /dev/null || exit 1"
      interval: 10s
      timeout: 5s
      retries: 3
    command: php -d upload_max_filesize=10G -d post_max_size=10G -S 0.0.0.0:8080 -t /var/www/html
    environment:
      - TZ
      - ADMINER_DEFAULT_SERVER=mysql
 ```
