### ISSUE TITLE
adminer 5.0.6 broken for csv export

### ISSUE THREAD

**Issue by snaeil** [TimWolla/docker-adminer#200]
Using adminer `5.0.6` via docker behind an docker nginx-reverse-proxy, I just experienced that exporting my database was not working anymore, as the logs show:

```
myapp-adminer-1  | [Tue Mar 25 12:10:39 2025] [::ffff:172.18.0.29]:60734 [200]: POST /?server=core_db&username=root&db=mydb&dump=clinic - Uncaught Error: Cannot access private property Adminer\TmpFile::$size in /var/www/html/adminer.php:1342
myapp-adminer-1  | Stack trace:
myapp-adminer-1  | #0 /var/www/html/adminer.php(1382): Adminer\tar_file('affected_depend...', Object(Adminer\TmpFile))
myapp-adminer-1  | #1 /var/www/html/index.php(52): require('/var/www/html/a...')
myapp-adminer-1  | #2 {main}
myapp-adminer-1  |   thrown in /var/www/html/adminer.php on line 1342
```

When I use the image with tag `4` everything is working again as expected.

Is this a problem with this repo since there were a lot of changes lately?

`docker-compose.yml` looks like this:

```yml
services:
  adminer:
    depends_on:
      core_db:
    environment:
      ADMINER_DEFAULT_SERVER: core_db
      LETSENCRYPT_HOST: ${ADMINER_ADDRESS}
      TZ: ${TZ}
      VIRTUAL_HOST: ${ADMINER_ADDRESS}
    image: docker.io/adminer:latest
    networks:
      core: null
    ports:
      - mode: ingress
        protocol: tcp
        published: "8888"
        target: 8080
    restart: "no"
  core_db:
    environment:
      MYSQL_DATABASE: mydb
      MYSQL_PASSWORD: ${CORE_DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${CORE_DB_ROOT_PASSWORD}
      MYSQL_USER: myuser
      TZ: ${TZ}
    image: docker.io/mariadb:10.6
    networks:
      core: null
    ports:
      - mode: ingress
        protocol: tcp
        published: "3306"
        target: 3306
    restart: always
```

Also the css design apparently changed using the latest docker image to some blue'ish one - was it intended to go away from the previous white default?
