### ISSUE TITLE
Activate firebird

### ISSUE THREAD

**Issue by evheniu** [TimWolla/docker-adminer#209]
How can be enabled firebird plugin ?

I'm trying with next compose file

```
services:
  adminer:
    container_name: adminer
    # image: adminer
    build:
      context: .
      dockerfile: Dockerfile
    user: adminer:adminer
    restart: always
    ports:
      - 80:8080
    environment:
      ADMINER_PLUGINS: tables-filter tinymce firebird
      ADMINER_DESIGN: nette
    volumes:
      - E:\docker\adminer\data\firebird.php:/var/www/html/plugins-enabled/firebird.php
  
```
But always have error 
```
adminer  | Unable to find plugin file "firebird".
adminer exited with code 0
```
