### ISSUE TITLE
can't connect fastcgi to nginx container

### ISSUE THREAD

**Issue by DashingNelson** [TimWolla/docker-adminer#35]
Hello,
I am using a docker composer file to use adminer fastcgi by using a nginx image but can't seem to figure it out as to why it is not working. Here is my docker composer file

```
#Use root/example as user/password credentials
version: '2.2'  
  web:
    image: nginx:latest
    ports:
        - "8000:80"
    volumes:
        # - ./code:/code
        - ./site.conf:/etc/nginx/conf.d/site.conf
    links:
        - adminer
  adminer:
     image: adminer:fastcgi
     ports:
        - 9000:9000
```

here is my site.conf file

```
server {
    index index.php;
    server_name 192.168.99.100;
    error_log  /var/log/nginx/error.log;
    access_log /var/log/nginx/access.log;

    location ~ \.php$ {
        try_files $uri =404;
        fastcgi_split_path_info ^(.+\.php)(/.+)$;
        fastcgi_pass adminer:9000;
        fastcgi_index index.php;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param PATH_INFO $fastcgi_path_info;
    }
}
```

what am i doing wrong?
