### ISSUE TITLE
Container is in an endless restart-loop

### ISSUE THREAD

**Issue by stevleibelt** [TimWolla/docker-adminer#40]
Hey, I just wanted to use adminer in a simple docker-compose.yml stack:

```
version: '3.7'

services:
    adminer_application:
        container_name: example-adminer
        hostname: adminer.application
        image: adminer:4
        ports:
            - 8080:8080
        restart: unless-stopped
    mysql_dbms:

        command: --default-authentication-plugin=mysql_native_password
        container_name: example-mysql
        environment:
            MYSQL_USER: foo
            MYSQL_PASSWORD: bar
            MYSQL_ROOT_PASSWORD: bar
        hostname: mysql.database
        image: mysql:8
        restart: unless-stopped
        volumes:
            - ./../../data/mysql:/var/lib/mysql
```

While the mysql container is running great, the adminer container is in an endless restart loop.

When I comment out the "restart: unless-stopped" and try to start it with:
```
docker container start -a example-adminer
```

I get this output:
```
[Wed Sep 19 09:57:41 2018] Failed to listen on :::8080 (reason: php_network_getaddresses: getaddrinfo failed: Name does not resolve)
<br />
<b>Warning</b>:  Unknown: php_network_getaddresses: getaddrinfo failed: Name does not resolve in <b>Unknown</b> on line <b>0</b><br />
```

Same output is produced when I start the container with:
```
docker container start -i example-adminer
```

```
sudo netstat -tulp | grep -c 8080
```
Returns "0".

What am I doing wrong?
I've also tried it with no container_name or no hostname definition in the docker-compose.yml.

Here are some specs about my environemnt:

```
#docker --version
Docker version 18.06.1-ce, build e68fc7a21
#docker-compose --version
docker-compose version 1.22.0, build unknown
#uname -a
Linux <hostname> 4.14.70-1-lts #1 SMP Sat Sep 15 16:47:42 CEST 2018 x86_64 GNU/Linux
#cat /etc/issue
Arch Linux \r (\l)

```

Thanks in advance and especially for your work so far,
Stev

**Comment by stevleibelt** [comment]
Things start to work when I've changed the adminer section to:

```
    adminer_application:
        container_name: example-adminer
        hostname: adminer.application
        image: adminer:4
        ports:
            - 8080:8080
        restart: unless-stopped
        volumes:
            - ./../../data/adminer:/adminer
```

Is the example on the [docker hub](https://hub.docker.com/_/adminer/) outdated since this contains the following example configuration.

```
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
```
