### ISSUE TITLE
Connect to elastic search db

### ISSUE THREAD

**Issue by bartoszkubicki** [TimWolla/docker-adminer#51]
I have something like this:

```
    adminer:
        image: adminer
        ports:
          - ${ADMINER_PORT}:8080

    elasticsearch:
        build: docker/dockerfile/elasticsearch
        ports:
            - ${ELASTICSEARCH_PORT}:9200
        volumes:
            - elasticsearch_data:/usr/share/elasticsearch/data
            - elasticsearch_config:/usr/share/elasticsearch/config
```

and plus some mysql container. Everthing is fine, I can easily connect to mysql container, but I can't figure out how to explore elastic search db - does it need any special docker coniguration?
