### ISSUE TITLE
Could you update the image documentation to include all of the environment variables and what they do?

### ISSUE THREAD

**Issue by salimfadhley** [TimWolla/docker-adminer#52]
This would make it much easier to get started with the container: A simple list of each environment variable, along with it's intended use.

Thanks

**Comment by TimWolla** [comment]
Can you clarify what exactly you are missing? I believe the documentation in https://github.com/docker-library/docs/tree/master/adminer contains all the custom environment variables.

**Comment by agates4** [comment]
I am trying to define the Adminer connection in my `docker-compose` file. 

The only `env` documented is `ADMINER_DEFAULT_SERVER=mysql`

Is this the only `env` available to configure? Is this supposed to be the entire engine params?

**Comment by TimWolla** [comment]
> Is this the only `env` available to configure?

As documented here you can also configure the style and plugins: https://github.com/docker-library/docs/tree/master/adminer

> Is this supposed to be the entire engine params?

This is the only this that can be configured about the login and it's only there, because the default of `localhost` is absolutely useless in the context of Docker. If you'd like an automated login have a look at #13.

**Comment by agates4** [comment]
for local development and easy of onboarding developers (using docker to achieve that goal) how can we pass plugins through via the `docker-compose` file?

**Comment by TimWolla** [comment]
You'll need to either bind mount the plugin (or plugin configuration) into the container or compile it into a customer Dockerfile.

I don't know docker-compose and thus don't know whether there's an easier solution.

**Comment by GottZ** [comment]
> I am trying to define the Adminer connection in my docker-compose file.

i feel like this was left unnoticed in this issue since this is the actual reason i'm writing here right now.

to give you a small insight in how docker-compose works..

it magically links containers together and ensures they are started in correct order. it also does watchdog stuff.

now to kinda reflect what users like us desire:


```yml
version: '3.7'

networks:
  magic:

services:
  db:
    image: postgres:12.2
    restart: unless-stopped
    networks:
      - magic
    environment:
      POSTGRES_USER: $DB_USER
      POSTGRES_PASSWORD: $DB_PASS
    volumes:
      - ./postgresql/data:/var/lib/postgresql/data

  adminer:
    image: adminer:4.7.6
    restart: unless-stopped
    networks:
      - magic
    depends_on:
      - db
    ports:
      - 127.0.0.55:8080:8080
    environment:
      ADMINER_DEFAULT_SERVER: db
      ADMINER_DEFAULT_USER: $DB_USER
      ADMINER_DEFAULT_PASSWORD: $DB_PASS
      ADMINER_DEFAULT_TYPE: postgresql
      ADMINER_DEFAULT_PORT: 5432
      ADMINER_DEFAULT_DB: magic

  actual application:
    ...
```

why is it so hard to specify these defaults..

one might say "oh no but it's unsafe. don't do that"

i might reply: "oh no. you cannot access 127.0.0.55 anyways so why you bother"

**Comment by GottZ** [comment]
lol. just stumbled across this abandoned repository: https://github.com/michalhosna/adminer-docker

**Comment by TimWolla** [comment]
> to give you a small insight in how docker-compose works..

I am aware of what docker-compose is on a high level. “Not knowing” is rather “Never used”.

> why is it so hard to specify these defaults..

It's out of scope for this image which attempts to provide a “packaged Adminer”. The only bit that modifies the inner workings of Adminer is the replacement of the `localhost` default value. The remaining modifications do not touch Adminer itself, but rather create a symlink (style) or preconfigure the Adminer plugin array.

> one might say "oh no but it's unsafe. don't do that"

Yes, I consider hardcoding the credentials unsafe, because it's too easy to misconfigure.

**Comment by lucasbasquerotto** [comment]
@TimWolla I agree that being able to assign those settings, be it in environment variables or in a configuration file would be great. I already do that with phpMyAdmin and MySQL and it works great. I found adminer and found it great too, and it's very cool that it can connect to other databases aside from MySQL. But having to enter login and other stuff would be a pain in my case (especially when handling more than 1 server). 

The adminer service would be accessible only through a a private network and authenticated with basic auth, and we prefer to use the credentials of the basic auth for our private services (not only adminer) which are easier to rotate passwords (it's just a file) instead of having to rotate passwords on a per service basis, which would be much more complex and error prone when automating. We also use a protection at the reverse proxy layer against CSRF. Furthermore, the credentials to the database would be mostly read-only. So, I don't think it would be unsafe in our case.

> Yes, I consider hardcoding the credentials unsafe, because it's too easy to misconfigure.

In our use case we use ansible to automate the server deployment, the `docker-compose` file is generated from a template and the `.env` file that will have the password assigned is also created dynamically (and have the correct permissions) with variables coming from a trusted source, with the password encrypted in the source, so it's not hardcoded.

for me environment variables like @GottZ used would be really useful!

I'm not saying that it must be done just because of my use case, I'm just giving my 2 cents, but it seems there are more people with the same request, so I came here to give a feedback.

**Comment by edomato** [comment]
Looking for something else I stumbled with this issue :smile: 

I agree with Tim on this one that hardcoding credentials on files is unsafe.

Adminer is a web based management system for different databases done in PHP.

Saying that, what I do is, if I'm tired to enter the credentials at the login page all the time, I just save them with the browser option to remember credentials that is far more secure that having them around on a file.

Just my two cents :wink:

**Comment by pollier** [comment]
Being able to configure servers / plugins / credentials by using environment variables is just an absolute standard in the docker / kubernetes world, this is not unsafe, hardcoding here is a docker compose problem not an adminer one.

- As an Adminer user i want to use adminer on my company DB host without having to seek credentials that are rotated every day.
- As a devops i want to deploy adminer to my kubernetes cluster, the adminer pods must share credentials from my application secrets which are exposed as env vars or files
- As a devops i don't want to send DB credentials to people every day as adminer is deployed behind corporate SSO that already handle authentication & 2FA

**Comment by TimWolla** [comment]
@pollier I'm aware of the the concept of using environment variables to pass credentials and in the context of Kubernetes this might be safely done, because the are not directly exposed to the user and can be changed in a central location.

But Kubernetes is not the only way this Docker image is going to be consumed. I'm seeing and using this primarily as a development tool, because IMO one should not poke around in a production database manually, but properly reviewed scripts / Ansible Playbooks / whatever.

Further different consumers have different needs and Adminer contains a plugin system that allows you to configure the authentication to your needs. Here's a non-core plugin that should be able to do the trick: https://github.com/giofreitas/one-click-login. You can access environment variables in PHP using `$_ENV['stuff']`.

Anything that I'll build in the image will cause limitations for someone and diverge the image from the stock Adminer experience.

**Comment by cglacet** [comment]
> Yes, I consider hardcoding the credentials unsafe, because it's too easy to misconfigure.

Does that mean some people use adminer to access their database in production? I've always though adminer was only used locally to access a test database (with only mocked up data in it).

**Comment by TimWolla** [comment]
@cglacet 
> Does that mean some people use adminer to access their database in production?

Reading the comments above and also the other issues that are created in this repository: Yes, they do.

In fact for a local test database that is not reachable via the Internet the request to store credentials probably would be less important, because a username / password combination of `root:root` would be acceptable from a security perspective and it would also be easy enough to type in quickly.

**Comment by mtariqsajid** [comment]
these environments are not working are they implemented in this docker image of adminer? 
or they will be implemented in future ?

```yml
ADMINER_DEFAULT_USER: $DB_USER
ADMINER_DEFAULT_PASSWORD: $DB_PASS
ADMINER_DEFAULT_TYPE: msqyl

```

**Comment by mtariqsajid** [comment]
> user above p

they should support this it will much easy to set adminer with multiple docker images for development

**Comment by lucasbasquerotto** [comment]
I think this issue should be closed then (if the feature will not be implemented).

**Comment by DasSkelett** [comment]
Can we at least get
```
ADMINER_DEFAULT_USER: $DB_USER
ADMINER_DEFAULT_TYPE: msqyl
```
?

Not allowing configuration of the password is an argument I can understand, even though I don't agree.
But db type and user are not security sensitive (talking about the default postgres user in a dev env here), and would already solve most of the inconveniences I have with this Docker image.

**Comment by mk-pmb** [comment]
I guess the better path forward would be to request on the upstream Adminer repo to read config from environment variables. Requesting it here for just the docker image, for me seems to be the wrong place.

**Comment by mk-pmb** [comment]
However, I agree that the readme here should describe which env vars it adds, and what ways there are to configure upstream Adminer via env vars. (Even in case the latter currently is "none".)

**Comment by zipzit** [comment]
Here's my dilemma.  I need to be able to view, review and edit database content in initial development.  docker-compose.yml test:

```
version: "3.8"
services:
    mysql_db:
        image: mysql:latest
        ports: 
          -  3307:3307
        environment:
          -  MYSQL_ROOT_PASSWORD=secret
        volumes:
            - ./mysql_db_data:/var/lib/mysql
            
    phpmyadmin:
        image: phpmyadmin
        restart: always
        environment:
          PMA_HOST: mysql_db
          PMA_USER: root
          PMA_PASSWORD: secret
        ports:
          - 8081:80
          
    adminer_container:
        image: adminer:latest
        environment: 
            ADMINER_DEFAULT_SERVER: mysql_db
            ADMINER_DESIGN: galkaev
            ADMINER_PASSWORD: secret
            ADMINER_USERNAME: root
        ports: 
          - 8080:8080
          
volumes:
    mysql_db_data: {}
```

I understand the security issues.  Try this for yourself.  `docker-compose up -d` .  Then http://localhost:8080   (for adminer)   http://localhost:8081 (for phpmyadmin)   Am I looking at this wrong?  This failure to populate login/password seems to be a sales pitch (for those of us who are admittedly often busy) the use of phpmyadmin instead of adminer.  My focus needs to remain on coding a solution to the clients need not one off customizations of what should be standard tooling for my team.  Keep it simple, make it work.  Am I looking at this wrong?

**Comment by mk-pmb** [comment]
@zipzit

> Adminer, No go.

Indeed. Unfortunately the [main Adminer repo](https://github.com/vrana/adminer) is not open for issues, and [their Forum](https://sourceforge.net/p/adminer/discussion/) is cumbersome.
Nevertheless, the request for easy server config via environment variables is a feature request to upstream, i.e. Adminer itself, not for this docker wrapper.

@TimWolla
Considering how often this feature is requested here, I think it's even worth explaining in the readme, where to beg for this feature.

**Comment by agates4** [comment]
For my use case, because of this lack of docs, I switched to [SqlPad](https://github.com/sqlpad/sqlpad)

**Comment by TimWolla** [comment]
> However, I agree that the readme here should describe which env vars it adds, and what ways there are to configure upstream Adminer via env vars. (Even in case the latter currently is "none".)

@mk-pmb Feel free to propose changes as a PR [over in docker-library/docs](https://github.com/docker-library/docs/tree/master/adminer) and simply ping me so I can review them.

I think it's sufficiently explained though, all the available configuration knobs are documented and what's not documented isn't there. Pretty simple.

>  Keep it simple, make it work. Am I looking at this wrong?

@zipzit Not sure if you are looking at this wrong. Let me give a different PoV, though: I'm keeping this image simple by not adding a large number of additional configuration knobs you have to think about when setting up this image.

Additionally upstream Adminer's Number 1 priority is “Security”. Providing database credentials to anyone able to access Adminer does not really fit in there.

Maybe Adminer simply isn't for you? If phpMyAdmin with its configurability better solves your requirements/problems, then use phpMyAdmin.

**Comment by TimWolla** [comment]
> @TimWolla In case SqlPad turns out useful for local development with prefilled login, should I add that to the docs PR as well?

I'd rather not reference any external products/alternatives, especially products that are not available as an _official_ Docker Image.

**Comment by zipzit** [comment]
Turns out for my use case (initial software development of a new application), VSCode has a plugin that enables simple queries to mySQL.  [Reference...](https://reposhub.com/javascript/misc/formulahendry-vscode-mysql.html). No Adminer, no Phpmyadmin, one less container.   No excessive security worries.  Less is more.  

No offense intended. Again many thanks to the Adminer team for an intriguing product.

**Comment by fnagel** [comment]
@TimWolla 

> As I explained many times before I won't be supporting these environment variables. I've explained possible solutions if you want to use these for your specific use-case.

It might help to document those possible solutions.

**Comment by jensenbox** [comment]
@TimWolla I do certainly appreciate your security concerns. I would like to propose that you add a section in the README that declares that there is one and only one Environment Variable that can be adjusted: `ADMINER_DEFAULT_SERVER`

As an option as well, perhaps you could also state something like: For all those that only want this for local development and will not be using this on anything other than localhost we suggest you use https://github.com/wodby/adminer

**Comment by mtariqsajid** [comment]
> I've explained possible solutions if you want to use these for your specific use-case.

can you please tell us where we can read those possible solutions ?

**Comment by jensenbox** [comment]
I ended up using a different docker image and it does everything we need for local development:

```yaml

  adminer:
    image: michalhosna/adminer # https://github.com/michalhosna/adminer-docker
    restart: always
    environment:
      ADMINER_DRIVER: pgsql
      ADMINER_USERNAME: debug
      ADMINER_PASSWORD: debug
      ADMINER_AUTOLOGIN: 1
      ADMINER_SERVER: ${COMPOSE_PROJECT_NAME}-postgresql
      ADMINER_DB: ${COMPOSE_PROJECT_NAME}
      ADMINER_NAME: ${COMPOSE_PROJECT_NAME}
    ports:
      - "127.0.0.1:8084:8080"
    depends_on:
      postgresql:
        condition: service_healthy
```

The addition of the `127.0.0.1` is important to make sure that if you are at a coffee shop or whatever that you are scoping access down to your local access only.

**Comment by GottZ** [comment]
@jensenbox this looks crazily similar to my proposal from [3 years ago in this issue here](https://github.com/TimWolla/docker-adminer/issues/52#issuecomment-598808641).

@TimWolla please don't take this too personal but your world-view on containers in this issue seems a little flawed.
most production deployments have some kind of ingress management with application and route specific permission grants to it's users.
for example, you won't be able to access my [router at home](https://speed.home.gottz.de) without going through my authenticator first.
a friend of mine with an account on my authenticator will also not get into my router but will be able to access several other resources that I've granted to their account.

user access control and role based access control are topics, that are rarely transparent to applications in deployment. especially ones like phpmyadmin, adminer and so on.
This is a good thing. Why would the Application even need to care about the complicated topic of authentication, if a Service in front of it is already taking care of it.

Also... if you setup something like adminer or phpmyadmin or what ever up in production, it has one specific reason:
The application accessing the database might not have a properly built admin interface.
This is mostly the case in non-consultant work, like internal applications, or applications without non-programmers as administrators.

access control is out of scope for adminer.
it cannot deal with saml, oauth, webauthn, reverse proxy authentication and so on.. so why enforce something as low as password authentication?
in some cases, it might not even be able to access the authentication server for backend login confirmation if permissions were set restrictive af..

for example, it would be much wiser to have a popup like this in adminer:
![image](https://github.com/TimWolla/docker-adminer/assets/559564/3a0ff07a-9f8f-4608-b3d1-bf0deb99801e)
if default credentials were supplied, rather than strictly preventing the use of default credentials at all.

saying that default credentials are a bad thing is your opinion but not a fact, that reflects common use-cases.
suggesting to use root:root in test environments is also opinionated and in many ways bad advice.
suggesting to write your own docker image to include a plugin that does this automatically is also opinionated and leaves a bad taste of outdated images behind, because someone got to trigger a image re-build when upstream updates, and not everyone has sufficient tooling for that.

so.. that's my 2 cents.

don't feel attacked by this please.

I just can't stand enforcement of password authentication in a world that has moved beyond passwords at this point.

**Comment by TimWolla** [comment]
I'm not taking this personal, but I naturally disagree. I'm not going to link to the heaploads of articles of improperly secured databases out in the Internet. By posting this comment on this issue tracker you're likely already above-average knowledge with regard to “how to properly run servers and how to perform authentication”. However naturally not everyone is above-average and from experience any type of warning message is ignored anyway. I don't want to be a contributing factor to databases being exposed and PII stolen and sold on the dark net. Defaults matter and in the end I'm going to be blamed for shipping something with insecure defaults.

Also, keep in mind that I do not develop Adminer itself.

**Comment by mk-pmb** [comment]
I agree that the it shouldn't be the image authors' responsibility to make these decisions. Rather, docker should supply its users with an easy (easier?) way to monkey-patch the relevant parts of an image.

**Comment by GottZ** [comment]
what about docker secrets then?
https://docs.docker.com/compose/use-secrets/

**Comment by TimWolla** [comment]
That would still require quite a bit of custom code to be written and careful checking that the secrets do not leak anywhere.

**Comment by DaDummy** [comment]
If anyone picks this up, maybe add this to the documentation to satisfy the common feature request raised in this issue:

In case you prefer to have auto-login for your dev deployments, you'll need to create your own Dockerfile deriving from this one. Simply put these two files in a folder and reference it using e.g. `build:context:` in your docker-compose:

---
`my-adminer-image/Dockerfile`
```Dockerfile
FROM adminer

RUN mv /var/www/html/index.php /var/www/html/entrypoint.php
COPY index.php /var/www/html/
```

`my-adminer-image/index.php`
```php
<?php
if(!count($_GET)) {
  $_POST['auth'] = [
    'server' => $_ENV['ADMINER_DEFAULT_SERVER'] ?? 'db',
    'username' => $_ENV['ADMINER_USERNAME'] ?? 'root',
    'password' => $_ENV['ADMINER_PASSWORD'] ?? '',
    'driver' => $_ENV['ADMINER_DRIVER'] ?? 'server',
    'db'    => $_ENV['ADMINER_DB'] ?? '',
  ];
}

require('./entrypoint.php');
```

---
Example Usage:

```yaml
version: "3.2"

services:
  db:
    image: mariadb
    environment:
      MARIADB_DATABASE=mydb
      MARIADB_ROOT_PASSWORD=root

  adminer:
    build:
      context: my-adminer-image
    environment:
      - ADMINER_DEFAULT_SERVER=db
      - ADMINER_DRIVER=server # server is adminer-speak for 'mysql'
      - ADMINER_USERNAME=root
      - ADMINER_PASSWORD=root
      - ADMINER_DB=mydb
    ports:
      - 8080:8080
    depends_on:
      - db
```

Cheers!
