### ISSUE TITLE
adminer:fastcgi don't working in my stack with php-fpm

### ISSUE THREAD

**Issue by schel4ok** [TimWolla/docker-adminer#88]
I have docker-compose for custom webserver with mariadb, nginx, php:7.4-fpm, adminer and some other nextra containers.

When I have setup like below everything works well and adminer is accessible in browser http://localhost:8080
```
version: '3.5'

services:

  mariadb:  
    image: mariadb
    .... some other settings ...
    networks:
      - internal

  adminer:
    image: adminer
    container_name: adminer
    depends_on:
      - mariadb
    environment:
      ADMINER_DEFAULT_SERVER: mariadb
      TZ: ${WORKSPACE_TIMEZONE}
    ports:
      - 8080:8080
    restart: always
    networks:
      - internal

  nginx:
    container_name: nginx
    build:
      context: ./nginx
    .... some other settings ...
    networks:
      - internal

  php:  
    container_name: php
    build:
      context: ./php  # FROM php:7.4-fpm
      args:
        PHPVERSION: "7.4"        # with php-7.4 compatible xdebug-2.9.1
        XDEBUGVERSION: "2.9.1"   # with php-7.3 compatible xdebug-2.7.1
    working_dir: /var/www
    environment:
      XDEBUG_CONFIG: "remote_host=192.168.220.1 remote_enable=1"
      PHP_IDE_CONFIG: "serverName=Docker"
      TZ: ${WORKSPACE_TIMEZONE}
    volumes:
      - ./.ssh:/home/www-data/.ssh
      - ${PROJECTS}:/var/www
    restart: always
    networks:
      - internal

networks:
  internal:
    name: webserver
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.220.0/28
```

But when I change adminer to adminer:fastcgi then in http://localhost:9000 I have nothing
```
    image: adminer:fastcgi
    ports:
      - 9000:9000
```
