### ISSUE TITLE
adminer in docker - suddenly no connection possible

### ISSUE THREAD

**Issue by IcedEarth** [TimWolla/docker-adminer#90]
Hi,

I was using the adminer docker image on my raspberry pi for quite some time without any problem. At some point it was not possible to use access the adminer pagte anymore. It just loads and loads without coming to and result. When I restart the container I can load the page once, but it is stuck in the loading loop again immediatly after. It looks like, adminer is closing the connection after the POST...

In the docker log it looks like this:
```
[Sat Jul 11 15:59:36 2071] PHP 7.4.14 Development Server (http://[::]:8080) started
[Sat Jul 11 15:58:32 2071] [::ffff:192.168.178.30]:53227 Accepted
[Sat Jul 11 15:47:36 2071] [::ffff:192.168.178.30]:53227 [403]: GET /?server=mariadb&username=fhem&db=fhem&sql=
[Sat Jul 11 15:56:56 2071] [::ffff:192.168.178.30]:53227 Closing
[Sat Jul 11 15:58:32 2071] [::ffff:192.168.178.30]:53228 Accepted
[Sat Jul 11 15:58:32 2071] [::ffff:192.168.178.30]:53229 Accepted
[Sat Jul 11 15:47:36 2071] [::ffff:192.168.178.30]:53228 [304]: GET /?file=default.css&version=4.7.8
[Sat Jul 11 15:56:56 2071] [::ffff:192.168.178.30]:53228 Closing
[Sat Jul 11 15:58:32 2071] [::ffff:192.168.178.30]:53230 Accepted
[Sat Jul 11 15:47:36 2071] [::ffff:192.168.178.30]:53229 [304]: GET /?file=functions.js&version=4.7.8
[Sat Jul 11 15:56:56 2071] [::ffff:192.168.178.30]:53229 Closing
[Sat Jul 11 15:58:32 2071] [::ffff:192.168.178.30]:53226 Accepted
[Sat Jul 11 15:55:36 2071] [::ffff:192.168.178.30]:53230 [200]: GET /adminer.css?v=-416286184
[Sat Jul 11 15:58:08 2071] [::ffff:192.168.178.30]:53230 Closing
[Sat Jul 11 15:47:36 2071] [::ffff:192.168.178.30]:53226 [302]: POST /?server=mariadb&username=fhem&db=fhem&sql=
[Sat Jul 11 15:56:56 2071] [::ffff:192.168.178.30]:53226 Closing
[Sat Jul 11 15:58:32 2071] [::ffff:192.168.178.30]:53231 Accepted
```

This is how i deploy the adminer container from a docker-compose
```
version: '3'

services:
    adminer:
        image: adminer:latest
        container_name: adminer
        labels:
            -  com.centurylinklabs.watchtower.enable=true
        restart: unless-stopped
        ports:
            - 8082:8080
        networks:
            - fhem-network
        environment:
            - ADMINER_DESIGN=rmsoft
            - ADMINER_DEFAULT_SERVER=fhem
```

I also tested to deploy a docker-compose with only adminer. In this scenario I observe the same behavior.

Any ideas on this?

All the best
