### ISSUE TITLE
How to properly connect css in fastcgi mode?

### ISSUE THREAD

**Issue by yareg-com** [TimWolla/docker-adminer#91]
I use adminer:fastcgi with caddy, both in docker containers and can't figure out how to properly connect adminer.css. The only way I managed to get it working is via volume but in that case the contents of the volume is not updated automatically when the adminer container is upgraded. What is the best practice to achieve this?

Here's my Caddyfile snippet:

```
redir /adminer /adminer/

route /adminer/* {
    uri strip_prefix /adminer

    php_fastcgi adminer:9000 {
        root /var/www/html
    }
}
```
Trying to solve the problem using volume I did like this:

Caddyfile:

```
redir /adminer /adminer/

  route /adminer/* {
      uri strip_prefix /adminer
      root * /adminer

      file_server @static

      php_fastcgi adminer:9000 {
          root /var/www/html
      }
  }
```

docker-compose.yml:

```
volumes:

  adminer:

services:

  caddy:
    image: caddy:2.3.0
...
    volumes:
      - adminer:/adminer:ro

 adminer:
    image: adminer:fastcgi
...
    volumes:
      - adminer:/var/www/html
```

Thanks in advance!
