### ISSUE TITLE
ARM build issue introduced between 4.7.7 and 4.7.8

### ISSUE THREAD

**Issue by stewart123579** [TimWolla/docker-adminer#96]
I'm unable to get adminer to load to the login screen for releases 4.7.8+ on a raspberry pi (ARM)

There's no error message, the browser just keeps trying to load.  `docker stats` has the container maxing the CPU out at 100%.

**To reproduce:**
Use the docker-compose recommended by postgres (https://hub.docker.com/_/postgres) and visit `<raspi-IP>:8080`

```
# Use postgres/example user/password credentials
version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example

  adminer:
     # image: adminer:4.7.6  # Works
    # image: adminer:4.7.7  # Works
    image: adminer:4.7.8  # FAILS
    restart: always
    ports:
      - 8080:8080
```

I can reproduce in Firefox, Chrome and Safari and via curl on the (raspi) localhost and remotely.

This does not seem to impact x86 releases.
