### ISSUE TITLE
Cannot pull Hydra design to docker-adminer

### ISSUE THREAD

**Issue by khangahs** [TimWolla/docker-adminer#99]
```
 adminer:
    depends_on:
      - db
    image: adminer:latest
    environment:
      ADMINER_DEFAULT_SERVER: db
      ADMINER_DESIGN: hydra //This one
    restart: always
    ports:
      - "8086:8080"
```

I cannot pull the design on Docker, any suggestion?
